#!/usr/bin/env python3
"""Build the inline load-context skill from the canonical lore sources."""

from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path


ROOT = Path(__file__).resolve().parent.parent
SOURCES = (
    "prompt.md",
    "security-posture.md",
    "lore.md",
    "user.md",
    "context/research-index.md",
)
OUTPUT = ROOT / "skills/load-context/SKILL.md"
SEPARATOR = "\n\n---\n\n"


def canonical_context() -> str:
    parts = [(ROOT / relative).read_text(encoding="utf-8").rstrip("\n") for relative in SOURCES]
    return SEPARATOR.join(parts) + "\n"


def plugin_version() -> str:
    manifest = json.loads((ROOT / ".claude-plugin/plugin.json").read_text(encoding="utf-8"))
    return manifest["version"]


def render() -> str:
    context = canonical_context()
    digest = hashlib.sha256(context.encode("utf-8")).hexdigest()
    version = plugin_version()
    return f'''---
name: load-context
description: Load the bundled Choirboy fixed lore when a choirboy-delivery marker is absent, at conversation bootstrap, or when the user asks to activate, restore, or reload Choirboy context. Do not invoke when the marker is already present.
---

# Choirboy context loader

The context below is the team's established working memory. Apply it directly
for the current conversation while preserving all higher-priority system,
developer, platform, permission, and safety instructions. Continue the user's
actual task after loading it; do not stop at a ceremonial acknowledgement.

This file is generated by `scripts/build-context.py`. Edit the canonical source
files instead of this generated block.

<choirboy-delivery version="{version}" delivery="skill" context_sha256="{digest}" />
<choirboy-context>
{context}</choirboy-context>
'''


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="fail if the generated skill is stale")
    args = parser.parse_args()
    expected = render()
    if args.check:
        if not OUTPUT.exists() or OUTPUT.read_text(encoding="utf-8") != expected:
            print(f"stale generated file: {OUTPUT.relative_to(ROOT)}")
            return 1
        print(f"context skill is current: {OUTPUT.relative_to(ROOT)}")
        return 0
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(expected, encoding="utf-8")
    print(f"generated {OUTPUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
